[alembic]
script_location = ./alembic
version_locations = ./app/database/migration
file_template = %%(slug)s_%%(year)d_%%(month)d_%%(day)d_%%(hour)d_%%(minute)d_%%(second)d
output_encoding = utf-8
sqlalchemy.url = postgresql+psycopg://user:password@database:5432/schema

# Declaración de loggers disponibles
[loggers]
keys = root,sqlalchemy,alembic

# Declaración de handlers disponibles
[handlers]
keys = console

# Declaración de formatters disponibles
[formatters]
keys = generic

# Configuración del logger raíz
[logger_root]
level = WARN
handlers = console
qualname = root

# Configuración del logger de SQLAlchemy
[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy

# Configuración del logger de Alembic
[logger_alembic]
level = INFO
handlers = console
qualname = alembic

# Configuración del handler de salida por consola
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

# Formato estándar para los mensajes de log
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S