services:

  database:
    image: postgres:18-bookworm
    container_name: database
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_SCHEMA}
      POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - database_data:/var/lib/postgresql
    networks:
      - ${COMPOSE_NAME}_network

  ${CONTAINER_SHELL}:
    build:
      context: .
    image: uv-debian
    container_name: ${CONTAINER_SHELL}
    user: "${UID}:${GID}"
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
    environment:
      # Variables de localizacion
      LANG: C.UTF-8
      TZ: Europe/Madrid
    volumes:
      # Directorio de trabajo
      - ./workdir:/workdir
      # Directorios de configuracion de Visual Studio Code y Git locales
      - ${HOME}/.vscode-server:${HOME}/.vscode-server
      - ${HOME}/.gitconfig:${HOME}/.gitconfig
    depends_on:
      - database
    networks:
      - ${COMPOSE_NAME}_network
    working_dir: /workdir

volumes:
  database_data:

networks:
  ${COMPOSE_NAME}_network:
    name: ${COMPOSE_NAME}_network
    driver: bridge