# Imagen base UV Debian
FROM ghcr.io/astral-sh/uv:python3.12-trixie-slim

    # Eliminar usuario con UID 1000 si existe
    RUN if getent passwd "${UID}" >/dev/null; then \
            userdel -r "$(getent passwd "${UID}" | cut -d: -f1)" || true; \
        fi \
        && if getent group "${GID}" >/dev/null; then \
            groupdel "$(getent group "${GID}" | cut -d: -f1)" || true; \
        fi

    # Instalacion paquetes desarrollo
    RUN apt-get update \
        && apt-get install -y --no-install-recommends \
            # Dependencias de DevContainers
            ca-certificates \
            curl \
            git \
            wget \
        # Limpieza de cache
        && rm -rf /var/lib/apt/lists/*

    # Crear usuario con UID, nombre y alias proporcionados, además de personalizar el shell
    RUN useradd -m -U -u ${UID} -s /bin/bash ${USER} \
        && echo 'PS1="\w # "' >> /home/${USER}/.bash_aliases \
        && echo "alias uv-run-fastapi-dev='uv run fastapi dev --host 0.0.0.0'" >> /home/${USER}/.bash_aliases \
        && chown ${USER}:${USER} /home/${USER}/.bash_aliases

# Mantener contenedor vivo
CMD ["tail", "-f", "/dev/null"]